name: "Release"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

env:
  GO_VERSION: "1.18"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Bootstrap all project dependencies
        run: make bootstrap

      - name: Build
        run: |
          if [[ "${GITHUB_REF}" = refs/tags/v* ]]; then
            make release
          else
            make RELEASE_FLAGS="--snapshot" release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/**/*
